name: flutter_rapidsnark_example
description: "Demonstrates how to use the flutter_rapidsnark plugin."
version: 0.0.1-alpha.1+3
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

environment:
  sdk: '>=3.3.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  flutter_rapidsnark:
    path: ../

  cupertino_icons: ^1.0.6
  path_provider: ^2.1.3

dev_dependencies:
  integration_test:
    sdk: flutter
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/circuit_final.zkey
    - assets/verification_key.json
    - assets/witness.wtns
