name: flutter_rapidsnark
description: "Rapidsnark Flutter Plugin"
version: 0.0.1-beta.3
homepage: https://github.com/iden3/flutter-rapidsnark

environment:
  sdk: '>=2.12.0 <4.0.0'
  flutter: '>=2.0.0'

dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.1.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  plugin:
    platforms:
      android:
        package: com.rapidsnark.flutter_rapidsnark
        pluginClass: FlutterRapidsnarkPlugin
      ios:
        pluginClass: FlutterRapidsnarkPlugin
